services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-agent
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FILE_UPLOAD_DIR=/app/uploads
      - OPENAI_API_KEY=${OPENAI_API_KEY}
