spring:
  application:
    name: DocAgent
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
file:
  upload-dir: /Users/arkadiuszrogacki/IdeaProjects/doc-agent/uploads/
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o
      log-requests: true
      log-responses: true
logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
server:
  error:
    include-message: always
