spring:
  application:
    name: DocAgent
file:
  upload-dir: /resources/uploads
langchain4j:
  open-ai:
    chat-model:
      api-key: 0
      model-name: gpt-4o
      log-requests: true
      log-responses: true
logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
